### ISSUE TITLE
TBAStatus causing crashes at random moments (Unexpectedly found nil while unwrapping an Optional value)

### ISSUE THREAD

**Issue by anas-merbouh** [the-blue-alliance/the-blue-alliance-ios#124]
let defaultStatusJSON: [String: Any] = [
            "android": [
                "latest_app_version": -1,
                "min_app_version": -1
            ],
            "current_season": currentYear,
            "down_events": [],
            "ios": [
                "latest_app_version": -1,
                "min_app_version": -1
            ],
            "is_datafeed_down": false,
            "max_season": currentYear
        ]
      
        return TBAStatus(json: defaultStatusJSON)!

2018-04-22 20:01:27.370989-0400 the-blue-alliance-ios[60034:14759816] [error] warning:  View context accessed for persistent container TBA with no stores loaded
CoreData: warning:  View context accessed for persistent container TBA with no stores loaded
(lldb)

**Comment by ZachOrr** [comment]
Can you give me steps to replicate?

**Comment by anas-merbouh** [comment]
I literally just opened the app. However, this error can only occur during the app launch.

**Comment by ZachOrr** [comment]
I can't seem to replicate this one. Let me know if you see it again - maybe provide the full stack trace and some screenshots of threads

**Comment by ZachOrr** [comment]
Removing TBAStatus to have these things live in Firebase Remote Config (https://github.com/the-blue-alliance/the-blue-alliance-ios/commit/c01d35d6c2edd7ab0c610ba04a86742a2c9bfec8)
