### ISSUE TITLE
Don't display District Points option on non-district events

### ISSUE THREAD

**Issue by brandondean** [the-blue-alliance/the-blue-alliance-ios#16]

**Comment by ZachOrr** [comment]
Yesssss

~ Zachary Orr

**Comment by phil-lopreiato** [comment]
In the android app, we still show the district points with a disclaimer that they're purely hypothetical

https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/res/values/strings_districts.xml#L24
