### ISSUE TITLE
Initial build issue

### ISSUE THREAD

**Issue by Neilio3264** [the-blue-alliance/the-blue-alliance-ios#185]
Followed all the steps and can't seem to be able to run the project.
<img width="1552" alt="screen shot 2018-05-17 at 11 15 02 pm" src="https://user-images.githubusercontent.com/24238434/40215790-4414e8ac-5a28-11e8-9000-539b1e595722.png">

**Comment by ZachOrr** [comment]
You pulled in an old version of TBAKit. Fun `pod update`

**Comment by Neilio3264** [comment]
Still seem to have the same issue.

**Comment by ZachOrr** [comment]
Oh - sorry. I wasn’t looking close enough. I assumed it was a different issue I see sometimes.

It looks like you’re using the wrong version of Xcode. compactMap is new in Swift 4.1, which is in Xcode 9.3

**Comment by Neilio3264** [comment]
Ah, okay that makes sense now. I have been using 9.2

**Comment by ZachOrr** [comment]
I can update the README accordingly. I forgot what version of Swift ships with what version of Xcode. Sorry about that.
