### ISSUE TITLE
Include 3D touch support 

### ISSUE THREAD

**Issue by anas-merbouh** [the-blue-alliance/the-blue-alliance-ios#207]
- We could add Peek/Pop and in the view controllers contained in the Tab Bar controller and find a way to integrate Peek/Pop actions with myTBA (like adding a team to favorites). 
- For the quick actions, we could add a widget that allows the user to see the upcoming events to which his favorites teams participate **(post-prod feature)**.

**Comment by ZachOrr** [comment]
Can we add more detail to this? Where/how should we support 3D touch? Quick actions? Peek/pop within the app? Which views should peek/pop? Can we even handle this right now with the way our refresh pattern works?

**Comment by anas-merbouh** [comment]
Yep yep, I updated the comment !

**Comment by ecbcat20** [comment]
I feel like implementing the 3D touch and Force touch stuff is going to be interesting... Apple's libraries for that kind of stuff, to my knowledge is closed-source and difficult to find. If anyone knows an Apple dev, we could approach them.
Am I wrong?

**Comment by ZachOrr** [comment]
It's not. We all got access to 3D Touch APIs when Apple released them in iOS 9. https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/Adopting3DTouchOniPhone/

**Comment by ecbcat20** [comment]
ah my badx
-Evan
