### ISSUE TITLE
Internationalize the app

### ISSUE THREAD

**Issue by anas-merbouh** [the-blue-alliance/the-blue-alliance-ios#210]
- I created a Google Sheet to help us with localization. It contains both keys for iOS and Android alongside with their text both in english and french. 
- I also found a custom script that will allow us to export the Google Sheet with the right format depending on the platform you want to use these localizations with. 
- Post-production goal
- Link : https://docs.google.com/spreadsheets/d/1vBTV90DJAbNcxpX9LpTVGrYUtRpp4APIYj15WLXlBSc/edit?usp=sharing

**Comment by ZachOrr** [comment]
Internationalization is one of those things we might have to move slowly and methodically on... have we heard of anyone requesting internationalization? The web has been running for years in one language - it might be worth asking if they've ever gotten feedback from users they'd like to see other languages supported.

It's also worth looking in to automating this. Would something like [Shuttle](https://github.com/square/shuttle) work for us? Without automating translations, this could be a pretty big process overhead - we don't want to have to reach out to several people every time we add a new string in the app.

**Comment by ZachOrr** [comment]
I'm going to close this out - I don't foresee this being something on our roadmap for quite some time, if ever
