### ISSUE TITLE
No package.json found: Cannot audit a project without a package.json

### ISSUE THREAD

**Issue by sorianog** [the-blue-alliance/the-blue-alliance-ios#226]
## Repro Steps
- Install React Native dependencies 
   - `cd subtrees/the-blue-alliance-react && npm install && cd ../..`
- Run `npm audit` and/or `npm audit fix`

## Results
<img width="506" alt="screen shot 2018-09-22 at 8 38 06 am" src="https://user-images.githubusercontent.com/13261711/45917372-b3987700-be43-11e8-8b4a-3195086bbc9d.png">

## Expected
- Successful run of `npm audit` commands 
- Decreased amount of vulnerabilities

**Comment by sorianog** [comment]
@ZachOrr Doh, I'm such a noob. Here's the `package.json` in all its glory:

<img width="340" alt="screen shot 2018-09-22 at 9 31 59 am" src="https://user-images.githubusercontent.com/13261711/45917762-64a21000-be4a-11e8-9d7d-16b4e08e669c.png">

**Comment by ZachOrr** [comment]
For docs sake - fixed these outdated dependencies in https://github.com/the-blue-alliance/the-blue-alliance-react/pull/5 and https://github.com/the-blue-alliance/the-blue-alliance-ios/pull/227
