### ISSUE TITLE
Status bar disappears after watching any video in full screen

### ISSUE THREAD

**Issue by LTSENG01** [the-blue-alliance/the-blue-alliance-ios#231]
After going to any event and watching a YouTube video in full screen and closing, the status bar disappears.

[iOS 12, iPhone 6s Plus]

**Comment by ZachOrr** [comment]
This is probably a bug with the player library we use - I'm not sure it's still supported by YouTube. We might look in to finding a different one

https://github.com/youtube/youtube-ios-player-helper
