### ISSUE TITLE
Will this be up and running this season?

### ISSUE THREAD

**Issue by nathan815** [the-blue-alliance/the-blue-alliance-ios#32]
I'm wondering if this will be up and running any time this season? Week 1 of competitions are done, but there's still lots of competitions left and having a TBA iOS app would be awesome! I don't know anything about iOS development so I can't tell how far away this is from being finished. I wish I could help you guys finish this -- if I knew how to make iOS apps, I would definitely help!

**Comment by ZachOrr** [comment]
Hey Nathan! It might be tough to get a functioning app out to the public this season. We also have to keep in mind App Store review will add ~1 week to our process.

We're aiming to at least have a public beta this season. However, I can't give a date for that. Brandon and I are pretty busy.

**Comment by nathan815** [comment]
Hey Zach! Alright, that's cool. I completely understand.

P.S. I'm the main driver on team 5517 and I just realized that you were the MC at Kettering Week 2. Nice job out there!
