### ISSUE TITLE
Error on loading 1992 championship rankings

### ISSUE THREAD

**Issue by szechy** [the-blue-alliance/the-blue-alliance-ios#326]
Looks like there's an error loading the 1992 championship rankings. I also tried the '93, '94, '95, '96, '97, '98, '99, and '00 championships and there are also errors. It doesn't look like this data actually exists per the website, so this should probably be handled nicer (e.g. like the "No matches for event" text on the Matches tab). The '01 championships (divisions and Einstein) have this handled properly and say "No rankings for event".

![img_1231](https://user-images.githubusercontent.com/1274255/49192870-d5294980-f331-11e8-97b3-b1ac9372ad18.jpg)
![img_1232](https://user-images.githubusercontent.com/1274255/49192869-d5294980-f331-11e8-865f-025bd4d1e663.PNG)

**Comment by szechy** [comment]
Gotcha, that makes a lot of sense.

Per https://www.thebluealliance.com/apidocs/v3 and the `/event/{event_key}/rankings` endpoint, this also seems like an API bug. Would it also make sense to also tag this as an issue with the main TBA website/repo?

**Comment by ZachOrr** [comment]
Yes! File a ticket for tracking please. The two endpoints you're looking for are...

http://thebluealliance.com/api/v3/event/1992cmp/rankings
https://www.thebluealliance.com/api/v3/event/2001gal/rankings

**Comment by ZachOrr** [comment]
I've filed this at https://github.com/the-blue-alliance/the-blue-alliance/issues/2333 - I'm particularly interested in getting this fixed, but the easiest path forward for me is to remove logging for unexpected API responses
