### ISSUE TITLE
Settings VC Removes Tab Bar

### ISSUE THREAD

**Issue by BK1031** [the-blue-alliance/the-blue-alliance-ios#356]
When you click on settings, the tab bar is hidden with no way to leave the settings page.

**Comment by ZachOrr** [comment]
https://github.com/the-blue-alliance/the-blue-alliance-ios/commit/fba37e379ccdaebbc3ff5e8d88318daba8d1fe58

**Comment by ZachOrr** [comment]
This fix will ship in a build later today
