### ISSUE TITLE
Team count in search does not reset after removing the search term

### ISSUE THREAD

**Issue by Chris2fourlaw** [the-blue-alliance/the-blue-alliance-ios#428]
The counter for the # of teams in search does not reset after removing the search term.

## Expected Behavior

The counter should reset with new search terms. 

## Current Behavior

Team counter does not reset.

## Screenshots

[Screen Recording](
https://drive.google.com/file/d/1ETZ272l3SRl32pSYcu6GEYiTS4V8XAFC/view?usp=drivesdk)

## Steps to Reproduce

1. Search for a team
2. Remove the team from the search input
3. Notice how the team count remembers the previous search results

## Your Environment

* Device: iPhone XR
* iOS version: 12.2 beta
* TBA for iOS version: 1.0.3

## Context

Searching for a team.

## Possible Solution

Remove the counter or reset when team input is blank.

**Comment by ZachOrr** [comment]
Yeah - this is a weird known bug. I'll try to prioritize it. Thanks.

**Comment by Chris2fourlaw** [comment]
I’m betting it has to do with [this](
https://github.com/the-blue-alliance/the-blue-alliance-ios/blob/master/the-blue-alliance-ios/View%20Controllers/Teams/TeamsViewController.swift#L63).

**Comment by ZachOrr** [comment]
That LOC is not the problem. If it were that LOC, our search bar placeholder wouldn't have any text in it.

It has to do with the lifecycle around that `controllerDidChangeContent` method. For some reason, it's not getting called when we update our data source to have no predicate, via hitting the x with the search bar.
