### ISSUE TITLE
Event sorting switching weeks early

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance-ios#483]
## Expected Behavior

The event sorting in the Events container should switch to the next week after all events have been played for a current week

## Current Behavior

The week is being switched early

## Screenshots

![simulator screen shot - iphone xs - 2019-03-05 at 00 15 33](https://user-images.githubusercontent.com/516458/53782552-cc6d8400-3edb-11e9-9b00-43d0e3ad99df.png)

## Steps to Reproduce

1. Date: 3-5-19
2. Open Events TVC
3. Observe Week 2 is shown by default

## Possible Solution

My guess is with our sort we're grabbing the first event in a date range and looking at the week to determine which week to show, which isn't really right. We need to look for the earliest week in a certain date range.

In this example, we're grabbing events that end on/after March 5th. The first match is probably a Week 2 event. I think we need to add another layer of sorting where we grab the one with the earliest start date? Using "week" here is going to be problematic for CMP.

(Event sorting should be shared code)

**Comment by phil-lopreiato** [comment]
https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/fragments/EventsByWeekFragment.java#L165-L184
https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/Utilities.java#L206-L208
https://github.com/the-blue-alliance/the-blue-alliance-android/blob/master/android/src/main/java/com/thebluealliance/androidclient/helpers/EventHelper.java#L91-L106

For reference, here's how the Android app does this - it computes the competition week for the current day and uses that to set the active pager tab

**Comment by ZachOrr** [comment]
The way Android is doing this makes MUCH more sense then the iOS is doing sorting. We should look to refactor iOS to use dates less and use weeks more (a lot of the code is old - before Events had week properties)
