### ISSUE TITLE
Floating-point error on ranking score

### ISSUE THREAD

**Issue by andykmin** [the-blue-alliance/the-blue-alliance-ios#617]
Ranking score of teams at events sometimes encounter floating point errors. 

## Expected Behavior

Ranking score is calculated by the total ranking points divided by the number of games the team played. Ranking scores should be rounded/dropped to the nearest hundredth.

## Current Behavior

The ranking score is usually rounded correctly, however sometimes a floating-point error results in scores such as 0.8100...001

## Screenshots

![IMG_175DFE3153FE-1](https://user-images.githubusercontent.com/26666500/59809691-9a2f3900-92b6-11e9-875b-c211399ea9ee.jpeg)

## Steps to Reproduce

1. Go to Team@Event (e.g. Team 7686 @ 2019 San Francisco Regional)
2. Go to Summary
3. Go to Ranking Breakdown

## Your Environment

* Device: iPhone 8
* iOS version: 12.3.1
* TBA for iOS version: 1.1.3(99)

## Context

 
When the ranking score is a very long number, formatting is broken compared to other teams, especially in Event Ranking View.

**Comment by ZachOrr** [comment]
This is fixed - just not released yet https://github.com/the-blue-alliance/the-blue-alliance-ios/pull/502
