### ISSUE TITLE
Swipe left gesture to go back when in menus

### ISSUE THREAD

**Issue by MC42** [the-blue-alliance/the-blue-alliance-ios#874]
Submitting on behalf of a friend of mine:

"Can someone on the TBA team implement swipe right to go back a page on the TBA app. Would save me so much effort to have to reach all the way up and touch the back button as I watch my 43rd match video of the night because I miss robots :)"

**Describe the solution you'd like**
Some gesture to go trigger the back option would be great.

**Additional context**
"Honestly the app is incredible, give them props and a thanks from me"

**Comment by ZachOrr** [comment]
I’m not sure I understand the request - we use the default navigation controllers, which support swiping backwards

![image](https://user-images.githubusercontent.com/516458/82630468-c63af480-9bc0-11ea-81d9-2e274e992bf5.png)
