### ISSUE TITLE
TBA 3.0.0 Beta Crashes at Teams Event View

### ISSUE THREAD

**Issue by arnavs-0** [the-blue-alliance/the-blue-alliance-ios#892]
**Describe the bug**
TBA App crashes when looking at events from the team view.

**To Reproduce**
1. Go to Teams
2. Click on any team
3. Go to events
4. Click on any event listed
5. Crash Occurs

**Expected behavior**
Should lead you to the event page of the event

**Screenshots**
Video: [Link](https://drive.google.com/file/d/17KbVmJeQhA7T4OD_WQ21FReUgbg5pN0t/view?usp=sharing)

**Your Environment (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.0.1
 - TBA for iOS Version: 3.0.0

**Comment by ZachOrr** [comment]
Firebase crash for this https://console.firebase.google.com/project/tbatv-prod-hrd/crashlytics/app/ios:com.the-blue-alliance.tba/issues/ea6b22d8e02ec4bd31d668ef352acbd0
