### ISSUE TITLE
“No URL Found” for match videos

### ISSUE THREAD

**Issue by prateekma** [the-blue-alliance/the-blue-alliance-ios#912]
**Describe the bug**
Matches that have videos as viewed from the website don't show videos on the app. 

**To Reproduce**
1. Open a match that has a video as viewed from the website. 

**Expected behavior**
The video should show up in the box and open YouTube. 

**Screenshots**
![image](https://user-images.githubusercontent.com/19977330/123560773-58251180-d772-11eb-8550-3aa5bbe3ba64.png)

**Your Environment (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14.6
 - TBA for iOS Version: 3.0.1

**Additional context**
None

**Comment by ZachOrr** [comment]
This is likely an issue with `XCDYouTubeKit` being outdated.

**Comment by ehamwey** [comment]
https://github.com/0xced/XCDYouTubeKit/issues/548

Seems that this is because YouTube is requiring API keys to use XCDYouTubeKit going forward. We could add one, or we could switch to a different library. @ZachOrr?

**Comment by ZachOrr** [comment]
Fixed with https://github.com/the-blue-alliance/the-blue-alliance-ios/pull/926
