### ISSUE TITLE
When will information of 2022 Rapid React be supported

### ISSUE THREAD

**Issue by mendax1234** [the-blue-alliance/the-blue-alliance-ios#922]
**Is your feature request related to a problem? Please describe.**

l have downloaded this app on my iphone ,but it only has the event in Season 2020.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by reediculous456** [comment]
The 2020 season is the default for some reason but the 2022 data is still on there. 

Click up at the top
![image](https://user-images.githubusercontent.com/24629474/160235966-546c1f11-5c03-498b-b31b-b5221757c1fb.jpeg)

Then go back to years and choose 2022
![image](https://user-images.githubusercontent.com/24629474/160235971-40c04820-1910-417b-97b3-19ffc9d836bb.jpeg)

**Comment by mendax1234** [comment]
Got it , thanks!
