### ISSUE TITLE
District point calculations are incorrect

### ISSUE THREAD

**Issue by rutmanz** [the-blue-alliance/the-blue-alliance-ios#962]
**Describe the bug**
TBA does not calculate district points in the 2024 season correctly and provides counts and rankings that do not match frc-events. 

**To Reproduce**
Visit a district's ranking page (using PNW as an example, but it seems to be present on all of them) on both [TBA](https://www.thebluealliance.com/events/pnw#rankings) and [frc-events](https://www.thebluealliance.com/events/pnw#rankings), and observe where things don't line up. 9430, 1540, and 6831. As a similar issue, TBA seems to sort tied points differently as well. FRC Events Web shows 3588 and 4918 (district points from event) ahead of 9581 (team age points), but TBA shows them behind.

**Expected behavior**
The point value totals and breakdowns, as well as the sorting, matches the values shown on the frc-events webpage.

**Comment by ZachOrr** [comment]
Should be fixed via https://github.com/the-blue-alliance/the-blue-alliance/pull/5782
